---
apt_sources:
  -
    source: "deb http://archive.canonical.com/ lucid partner"
apt_upgrade: true
packages:
  - ant
  - build-essential
  - gawk
  - lesstif2-dev
  - libasound2-dev
  - libcups2-dev
  - libfreetype6-dev
  - libopenssl-ruby
  - libxml2-dev
  - libxslt-dev
  - libxtst-dev
  - mercurial
  - openjdk-6-jdk
  - ruby
  - ruby-dev
  - rubygems
  - zip
